### PR TITLE
Added StatusCodeError when receiving unexpected status code

### LINKED ISSUE #233: Allow retrieval of StatusCode in connection error
Currently, when a remote server returns an error status code when connecting, all we get is a meaningless ["Status code must be Switching Protocols" message](https://github.com/websockets-rs/rust-websocket/blob/master/src/client/builder.rs#L846). This leads to hard to debug issues like #160.

Instead, when a unexpected status code is encountered it should be returned so that the use can take appropriate action.

Example use case: I am connecting tons of websockets to a remote endpoint and I need to be able to receive the `429 Too many requests` status code to throttle back my rate of ws creation.

I'll make a PR.

### PR DESCRIPTION
**Pull request by jean-airoldie**
Fixes #233.

While this is theoretically a breaking change, I'm unsure if its that significant.

### CODE REVIEW

**Comment by vi** [comment]
I'll include it when I release #222-based version which also breaks error handling in user code.

**Comment by vi** [comment]
On the other hand, #236 also technically unstabilizing (`websocket` can start leaking username and password that was previously ignored), so bumping major version and releasing anyway with this as well.

**Comment by vi** [comment]
Published `v0.23.0`.

**Comment by jean-airoldie** [comment]
@vi Nice, thanks!

**Pull request merged**
