### PR TITLE
update to 2018 edition

### PR DESCRIPTION
**Pull request by hyyking**
update existing codebase to rust 2018 edition

### CODE REVIEW

**Comment by vi** [comment]
Note: this may bump minimum supported Rust version. Currently it works with 1.28.0, for example.

**Comment by vi** [comment]
Are there any substantial changes in this PR or just `cargo fix`-like ones?

**Comment by vi** [comment]
Also next major release of `rust-websocket` may be based on "split_in_two" branch.

**Comment by hyyking** [comment]
> Are there any substantial changes in this PR or just `cargo fix`-like ones?

Only cargo fix

> Note: this may bump minimum supported Rust version. Currently it works with 1.28.0, for example.

Right but since async/await will be hitting soon I think this will help work on the crate, people using older rust compilers will use older version of the crate

**Comment by vi** [comment]
Do you mean `futures 0.3` support? It is a bigger task than just being edition 2018.

**Comment by vi** [comment]
Merged, but Github failed to detect it.

**Pull request closed without merging**
