### PR TITLE
Fix server::async fmt by rustfmt

### PR DESCRIPTION
**Pull request by kpp**
rustfmt changed and the current code does not match its rules

### CODE REVIEW

**Comment by kpp** [comment]
ping

**Comment by kpp** [comment]
@vi ping

**Comment by vi** [comment]
@kpp, Acknowledged, but I haven't look at rust-websocket in a while.

Shall something be released urgently to unblock publishing of something else?

**Comment by kpp** [comment]
> Shall something be released

No. Just another improvement.

**Pull request merged**
