### PR TITLE
Add Send trait bounds to the Futures

### PR DESCRIPTION
**Pull request by tomaka**
Tokio's executor trait requires `Send` to be implemented on the future to be spawned.

### CODE REVIEW

**Comment by vi** [comment]
Does it limit ability to use rust-websocket with non-sendable underlying connection while single-threaded?

**Comment by tomaka** [comment]
@vi It does indeed. However I have yet to find any connection in the wild that isn't `Send`. Plus, as it has to be conservative, the `Executor` trait of tokio requires `Send` even when the executor doesn't in fact require `Send`.

**Comment by tomaka** [comment]
The ideal solution is not to use a `Box`, but that's a rather big change.

**Comment by vi** [comment]
> However I have yet to find any connection in the wild that isn't Send

Non-`Send` world is just one `RefCell` away. If a program is designed to be single-threaded, there may be no Mutex'es (with their poison and overhead, etc.), but Rc<RefCell> instead.

**Comment by tomaka** [comment]
On the other hand, right now it's impossible to use this library both in a multithreaded context and in a single-threaded context with the latest version of tokio.

**Comment by vi** [comment]
Will it stay that way with [Tokio reform](https://github.com/websockets-rs/rust-websocket/issues/165) done?

**Comment by vi** [comment]
One of the hacks that can be done is to let users to choose "Provide Send, but requre Send" or "Not provide Send, not require Send" as Cargo feature (like `#[cfg(feature="send")]`). The feature may be default-on.

**Comment by tomaka** [comment]
Using a feature is bad idea, because if a user pulls the websocket library once without the feature and once with the feature, then the feature will be enabled even on the side where it wasn't.

In other words, code that compiles with a feature disabled should always keep compiling with that feature enabled.

**Comment by tomaka** [comment]
Using a feature is bad idea, because if a user pulls the websocket library once without the feature and once with the feature, then the feature will be enabled even on the side where it wasn't.

In other words, code that compiles with a feature disabled should always keep compiling with that feature enabled.

**Comment by tomaka** [comment]
> Will it stay that way with Tokio reform done?

This change is "post tokio reform". You can consider it part of the reform.

**Comment by vi** [comment]
Shall Mutex-denial users use

```
/// Not actually safe, but we are not using threads anyway and library requires Send unconditionally
unsafe impl Send for SomeWrapper{}
```

hack? (like I [use](https://github.com/vi/websocat/blob/master/src/ws_client_peer.rs#L206) in my project)

It starts feeling that although theoretically one can use do Futures without Send with current_thread runtime, but in reality it not ecosystem-supported (like no_std - you can do no_std, but most dependencies bring in std)...

**Comment by dicej** [comment]
@vi You might want to consider https://crates.io/crates/send_wrapper as a safe alternative to `unsafe impl Send`.

**Comment by vi** [comment]
Published `websocket` v`0.20.4` with this change.

**Comment by tomaka** [comment]
That should be 0.21 strictly speaking, as there is a new trait bound requirement.

**Comment by vi** [comment]
Already released.

I plan to publish `0.21.0` with #186, and `0.22.0` from [@enzious](https://github.com/enzious/rust-websocket).

**Pull request merged**
