### PR TITLE
Remove deprecated usage of the "description" and "cause" functions

### PR DESCRIPTION
**Pull request by Mr-Leshiy**
Remove deprecated usage of the `description` function and replace it with `to_string` function.
Remove deprecated usage of the `cause` function and replace it with `source` function.

### CODE REVIEW

**Comment by vi** [comment]
Do usages of the deprecated `Error` methods cause any real problems or just the annoying messages?

**Comment by Mr-Leshiy** [comment]
@vi , currently just annoying messages, but it is possible that they will be removed later.

**Comment by vi** [comment]
I expected the crate to be still `edition=2015` (supporting legacy Rust versions), but now noticed that is `edition=2018`, so there versions below `1.31` are already unsupported. Since `Error::source` is `1.30`, that shouldn't bump MSRV, so this can be merged.

**Comment by vi** [comment]
Published `0.26.3`, but it is still in "deprecated, avoid usage" area.

**Pull request merged**
