### PR TITLE
Fix clippy attributes

### PR DESCRIPTION
**Pull request by sterlingjensen**
Update deprecated lint names and remove unnecessary cfg_attr(cargo-clippy)

### CODE REVIEW

**Comment by vi** [comment]
Doesn't it bump minimal Rust version from approximately 1.28 way up to 1.31?

**Comment by sterlingjensen** [comment]
No, 1.28 builds, it just warning about unknown lints.

**Comment by kpp** [comment]
@sterlingjensen would you please rebase your code to master? And it seems like clippy is available on stable.

**Comment by vi** [comment]
Primary reason for not merging was to support old versions of rustc (note that this crate is still edition 2015).

Now those old versions are really old.

**Pull request merged**
