### PR TITLE
Use tokio 0.1 (tokio reform updates)

### PR DESCRIPTION
**Pull request by surdus**
Related issue #165

### CODE REVIEW

**Comment by vi** [comment]
How does it compare to [this repository](https://github.com/enzious/rust-websocket/issues/6)?

**Comment by kellerkindt** [comment]
Thans @surdus , you made it available just as I needed it. I am currently using it in production and besides some sporadic disconnects (upstream write buffer fills up, which might be caused by another change of mine), its running fine.

**Comment by surdus** [comment]
> How does it compare to [this repository](https://github.com/enzious/rust-websocket/issues/6)?

It is just tokio related updates with fix of all compile warnings (there were some related to deprecated methods). In repo you mentioned there is also updates for new hyper version as I see and looks it is still required some work to do (rust show warnings for some unused variables and deprecated methods). But in general looks like it also use new tokio

**Comment by vi** [comment]
So this pull request is probably for version `0.22.0` and enzious's version may be `0.23.0` (or later), if it would be ready.

**Comment by vi** [comment]
`examples/async-client` and websocat get race condition after this.

Server (websocat is based on current rust-websocket version):

```
$ websocat -b ws-l:127.0.0.1:2794 literal:12345
websocat: Unfortunately, serving multiple clients without --exit-on-eof (-E) or with -U option is prone to socket leak in this websocat version
```

websockets-rs without bug (2f9ab02e124f9b64352d40bd85b9392d36d92a66):

```
$ strace -fo /dev/null target/debug/examples/async-client 
Connecting to ws://127.0.0.1:2794
Received Message: Binary([49, 50, 51, 52, 53])
Received Message: Close(None)
^C

$ strace -fo /dev/null target/debug/examples/async-client 
Connecting to ws://127.0.0.1:2794
Received Message: Binary([49, 50, 51, 52, 53])
Received Message: Close(None)
^C

$ strace -fo /dev/null target/debug/examples/async-client 
Connecting to ws://127.0.0.1:2794
Received Message: Binary([49, 50, 51, 52, 53])
Received Message: Close(None)
^C

$ strace -fo /dev/null target/debug/examples/async-client 
Connecting to ws://127.0.0.1:2794
Received Message: Binary([49, 50, 51, 52, 53])
Received Message: Close(None)
^C

$ strace -fo /dev/null target/debug/examples/async-client 
Connecting to ws://127.0.0.1:2794
Received Message: Binary([49, 50, 51, 52, 53])
Received Message: Close(None)
^C

$ strace -fo /dev/null target/debug/examples/async-client 
Connecting to ws://127.0.0.1:2794
Received Message: Binary([49, 50, 51, 52, 53])
Received Message: Close(None)
^C
```

rust-websocket with this pull request merged in:

```
$ strace -fo /dev/null target/debug/examples/async-client 
Connecting to ws://127.0.0.1:2794
^C

$ strace -fo /dev/null target/debug/examples/async-client 
Connecting to ws://127.0.0.1:2794
^C

$ strace -fo /dev/null target/debug/examples/async-client 
Connecting to ws://127.0.0.1:2794
^C

$ strace -fo /dev/null target/debug/examples/async-client 
Connecting to ws://127.0.0.1:2794
^C

$ target/debug/examples/async-client 
Connecting to ws://127.0.0.1:2794
Received Message: Binary([49, 50, 51, 52, 53])
Received Message: Close(None)
^C

$ target/debug/examples/async-client 
Connecting to ws://127.0.0.1:2794
Received Message: Binary([49, 50, 51, 52, 53])
Received Message: Close(None)
^C

$ target/debug/examples/async-client 
Connecting to ws://127.0.0.1:2794
Received Message: Close(None)
^C

$ target/debug/examples/async-client 
Connecting to ws://127.0.0.1:2794
Received Message: Binary([49, 50, 51, 52, 53])
Received Message: Close(None)
^C
```

**Pull request merged**
